---
title: "LC_MS_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r }
CalCurve1 <- read_csv("~/R/LC_MS/Data/CalCurve1.csv", 
    col_types = cols(X6 = col_skip(), X7 = col_skip(), 
        X8 = col_skip(), X9 = col_skip())) %>%
  slice(1:4)
View(CalCurve1)
```

```{r Calibration Curve}
CalCurve1 <- CalCurve1 %>% 
  pivot_longer(cols= 3:5, values_to= "PeakArea") %>%
  rename(Conc = "[Levoglucosan] (ug/mL)")

ggplot(CalCurve1, aes(x= Conc, y= PeakArea)) + theme_bw() + geom_point() + geom_smooth(method = lm, se = FALSE) + labs(x= "Concentration of Levoglucosan (µg/mL)", y = "Peak Area", title="Calibration Curve for Levoglucosan")

model <- lm(PeakArea ~ Conc, data= CalCurve1)  
slope <- model$coefficients[2]
intercept <- model$coefficients[1]
slope_std <- summary(model)$coefficients[2,2]
intercept_std <- summary(model)$coefficients[1,2]
equation <- tibble(slope, slope_std, intercept, intercept_std)

```

```{r}
SampleAreas <- read_csv("~/R/LC_MS/Data/sampleareas.csv")

SampleAreas <- SampleAreas %>%
  mutate(Concentration = (SampleAreas$Area - equation$intercept) / equation$slope, 
         Concentration_Error = Concentration*sqrt((equation$slope_std/equation$slope)^2 + (equation$intercept_std/equation$intercept)^2))

view(SampleAreas)
```

```{r Concentration in the Air}
SampleAreasAir <- SampleAreas %>%
  mutate(ConcAir = (Concentration * 2 *70)/24,
ConcAirError = (Concentration_Error * 2 * 70)/24)
```

```{r}
East <- SampleAreasAir %>%
  filter(str_detect(Location, "E"))
  East$Coast <- "E"

West <- SampleAreasAir %>%
  filter(str_detect(Location, "W"))
  West$Coast <- "W"

Date1750 <- SampleAreasAir %>%
  filter(str_detect(Location, "1750"))
  Date1750$Date <- "1750"

Date1950 <- SampleAreasAir %>%
  filter(str_detect(Location, "1950"))
  Date1950$Date <- "1950"

Date2020 <- SampleAreasAir %>%
  filter(str_detect(Location, "2020"))
  Date2020$Date <- "2020"
  
# use full_join to merge two datasets (use multiple times to merge more than two) and "by=" for all the columns to merge by  
  
CoastsMerged= full_join(East, West, by= c("Location", "Area", "Concentration", "Concentration_Error", "ConcAir", "ConcAirError", "Coast"))

Date1750Date1950Merged= full_join(Date1750, Date1950, by= c("Location", "Area", "Concentration", "Concentration_Error", "ConcAir", "ConcAirError", "Date"))

DatesMerged= full_join(Date1750Date1950Merged, Date2020, by= c("Location", "Area", "Concentration", "Concentration_Error", "ConcAir", "ConcAirError", "Date"))

AllMerged= full_join(DatesMerged, CoastsMerged, by= c("Location", "Area", "Concentration", "Concentration_Error", "ConcAir", "ConcAirError"))

```

```{r}
ggplot(AllMerged, aes(x= Date, y= ConcAir, fill= Date)) + theme_bw() + geom_point() + geom_boxplot() + facet_wrap(~Coast) + labs(x= "Date", y = "Levoglucosan (µg/M^3)", title="Levoglucosan Concentations By Date") 


ggplot(AllMerged, aes(x= Coast, y= ConcAir, fill= Coast)) + theme_bw() + geom_point() + geom_boxplot() + facet_wrap(~Date) + labs(x= "Coast", y = "Levoglucosan (µg/M^3)", title="Levoglucosan Concentations By Coast")
```


